### ISSUE TITLE
The while plugin is broken

### ISSUE THREAD

**Issue by pinn3apple** [Fierdetta/decor#4]
![image](https://github.com/user-attachments/assets/2d3b5c94-7e20-4af1-b56b-c3896c8225b8)
as you can see in the picture the decor effect category is bugged, the effects dont show up and opening up the settings for the plugin just crashes discord

**Comment by jenkuuuuuu** [comment]
yea jack knows already, also this is the vendetta plugin not sure why you're making an issue here 😭
![Screenshot_20241122_151932](https://github.com/user-attachments/assets/91f904b2-9ef7-493a-b3bf-042f6d0608df)
![Screenshot_20241122_151955](https://github.com/user-attachments/assets/6fe469c9-8d28-4228-8a07-c1a1228ee2a9)
![Screenshot_20241122_152008](https://github.com/user-attachments/assets/63b27143-4e24-462c-ae7b-03b02cd4a3a1)

**Comment by jackmthws** [comment]
Discord updated (or downgraded?) a library Decor depends on for Vencord. This should be fixed in the coming days. 
Decor for Vendetta (not Vencord) and it's derivatives is no longer supported.
